In [1]:
import warnings
warnings.filterwarnings("ignore")

## Imports

In [2]:
import math
import os
import time
import requests
import pandas as pd
import json
import numpy as np
from pathlib import Path
from typing import Optional, Dict, List, Union
from unidecode import unidecode
import matplotlib.pyplot as plt

import pandas_gbq
from google.auth import default
from google.cloud import bigquery
from google.api_core.exceptions import NotFound

In [3]:
from funcoes_escoragem import *

## Diretório

In [4]:
BASE_DIR = Path("data")
RAW_DIR = BASE_DIR / "raw"
TRUSTED_DIR = BASE_DIR / "trusted"
ANALYTICS_DIR = BASE_DIR / "analytics"

for path in [RAW_DIR, TRUSTED_DIR, ANALYTICS_DIR]:
    path.mkdir(parents=True, exist_ok=True)

## Google BigQuery

In [5]:
project_id = 'loft-dl-fintech'

# CredPago - Consulta Realizada**

In [6]:
query_credpago = f"""
WITH consulta_realizada AS (
    SELECT
        CAST(REGEXP_REPLACE(documento, r'[^0-9]', '') AS INT64) AS CPF_CNPJ,
        id_externo AS contract_id,

        MIN(DATE(data)) OVER (
            PARTITION BY id_externo
        ) AS requested_at,

        MAX(DATE(data)) OVER (
            PARTITION BY id_externo
        ) AS data_ultima_consulta,
        ARRAY_LENGTH(JSON_EXTRACT_ARRAY(CR.json_retornado, '$.pessoas')) AS qtd_proponentes,
        SAFE_CAST(JSON_EXTRACT_SCALAR(CR.request, '$.imovel.codigo_cidade_ibge') AS INT64) AS codigo_cidade_ibge,
        CR.*
    FROM `loft-dl-fintech.bronze_credpago_sortinghat.consulta_realizada` CR
    WHERE DATE(data) >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 WEEK)
    AND DATE(data) < CURRENT_DATE()
)

SELECT *
FROM consulta_realizada
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY contract_id
    ORDER BY 
        CASE WHEN model = 'BLEND_4' THEN 1 ELSE 2 END ASC,
        data DESC
) = 1
"""

credpago_df = pd.read_gbq(query_credpago, project_id=project_id)
credpago_df

,CPF_CNPJ,contract_id,requested_at,data_ultima_consulta,qtd_proponentes,codigo_cidade_ibge,score_imobiliaria,renda_considerada,model,id_externo,...,id_funcionalidade,_sdc_table_version,request,_sdc_received_at,_sdc_sequence,documento,rating,_sdc_batched_at,data,result
0,56102410068,4636770,2026-09-11,2026-09-11,2,4304705,NI,7192.500000000,HVA3,4636770,...,15,1786647574343,"{""valor_aluguel"":1600,""matchmaking_on"":false,""...",2026-09-11 18:00:35+00:00,1789149629263138898,56102410068,N,2026-09-11 18:03:50.810000+00:00,2026-09-11 08:32:00+00:00,DERIVAR
1,5251461054,4636834,2026-09-11,2026-09-11,2,4316907,NI,3425.000000000,HVA3,4636834,...,15,1786647574343,"{""valor_aluguel"":800,""matchmaking_on"":false,""p...",2026-09-11 18:00:35+00:00,1789149629463305979,05251461054,N,2026-09-11 18:03:50.832000+00:00,2026-09-11 08:45:24+00:00,DERIVAR
2,64712583053,4715383,2026-09-26,2026-09-26,1,4314902,NI,4384.000000000,BLEND_4,4715383,...,30,1786647574343,"{""principalDocument"":""64712583053"",""imobiliari...",2026-09-26 18:00:36+00:00,1790445634335169325,64712583053,C,2026-09-26 18:04:46.982000+00:00,2026-09-26 11:24:06+00:00,APROVAR
3,57566372815,4715444,2026-09-26,2026-09-26,1,4303103,NI,7261.000000000,BLEND_4,4715444,...,30,1786647574343,"{""principalDocument"":""57566372815"",""imobiliari...",2026-09-26 18:00:36+00:00,1790445634342483390,57566372815,E,2026-09-26 18:04:47.026000+00:00,2026-09-26 11:24:42+00:00,APROVAR
4,4207461450,4434613,2026-07-29,2026-07-29,1,3127701,B,8014.500000000,BLEND3_3,4434613,...,35,1786647574343,"{""valor_aluguel"":2700,""matchmaking_on"":false,""...",2026-08-13 19:38:43+00:00,1786649920639301170,04207461450,C,2026-08-13 19:42:28.031000+00:00,2026-07-29 08:21:09+00:00,DERIVAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379724,9619384474,4511804,2026-08-14,2026-08-14,1,2408102,NI,0E-9,BLEND3_4,4511804,...,33,1786647574343,"{""valor_aluguel"":3000,""matchmaking_on"":false,""...",2026-08-14 18:00:27+00:00,1786730421396912164,09619384474,E,2026-08-14 18:06:07.680000+00:00,2026-08-14 10:13:18+00:00,REPROVAR
379725,14853192697,4512104,2026-08-14,2026-08-14,1,4208906,C,4247.000000000,BLEND3_4,4512104,...,33,1786647574343,"{""valor_aluguel"":6890,""matchmaking_on"":false,""...",2026-08-14 18:00:27+00:00,1786730421959171723,14853192697,E,2026-08-14 18:06:07.808000+00:00,2026-08-14 10:45:29+00:00,REPROVAR
379726,73446769072,4519626,2026-08-17,2026-08-17,1,<NA>,NI,2192.000000000,BLEND_4,4519626,...,37,1786647574343,"{""principalDocument"":""73446769072"",""imobiliari...",2026-08-17 18:00:30+00:00,1786989623866126326,73446769072,E,2026-08-17 18:03:52.855000+00:00,2026-08-17 10:58:47+00:00,REPROVAR
379727,2036055605,4520552,2026-08-17,2026-08-18,1,3138203,D,2671.500000000,BLEND3_4,4520552,...,33,1786647574343,"{""valor_aluguel"":2000,""matchmaking_on"":false,""...",2026-08-18 18:00:31+00:00,1787076022400184521,02036055605,E,2026-08-18 18:05:12.338000+00:00,2026-08-18 08:34:44+00:00,REPROVAR
379728,2992163066,4528940,2026-08-18,2026-08-18,1,4316907,NI,0E-9,BLEND3_4,4528940,...,33,1786647574343,"{""valor_aluguel"":900,""matchmaking_on"":false,""p...",2026-08-19 08:00:28+00:00,1787126422690753262,02992163066,E,2026-08-19 08:02:48.140000+00:00,2026-08-18 15:07:20+00:00,REPROVAR

In [7]:
mask = credpago_df['contract_id'].astype(str).str.match(r'^\d+$')
credpago_df = credpago_df[mask].copy()
credpago_df['contract_id'] = credpago_df['contract_id'].astype(int)

## Quebrar JSON - Retornado

In [8]:
def unwrap_payload(obj):
    """Supports old format (message wrapper) and new format (root payload)."""
    if not obj:
        return None
    if isinstance(obj, dict) and "message" in obj:
        return obj["message"]
    return obj

def get_pessoas(obj):
    payload = unwrap_payload(obj)
    return (payload or {}).get("pessoas") or []

In [9]:
parsed = credpago_df["json_retornado"].apply(
    lambda x: json.loads(x) if pd.notna(x) and x else None
)

valid_parsed = parsed.dropna()
payload_parsed = valid_parsed.apply(unwrap_payload)

# json_normalize resets the index; preserve credpago_df labels for the join below
contrato_df = pd.json_normalize(payload_parsed.tolist(), sep="_")
contrato_df.index = payload_parsed.index
contrato_df = contrato_df.add_prefix("message_")  # keeps message_decisao, message_scores_*, etc.

pessoa_records = payload_parsed.apply(lambda x: (get_pessoas(x) or [{}])[0])
pessoa_df = pd.json_normalize(pessoa_records.tolist(), sep="_")
pessoa_df.index = payload_parsed.index
pessoa_df = pessoa_df.add_prefix("pessoa_")

In [10]:
valid = parsed.notna()
base_idx = credpago_df.loc[valid].index

pendencias = []
for idx, row in parsed[valid].items():
    for p in get_pessoas(row):
        if not isinstance(p, dict):
            continue

        serasa = p.get("anotacoesFinanceirasSerasa") or {}
        pend_list = serasa.get("PendenciasPagamentoPF") or []

        for pend in pend_list:
            if isinstance(pend, dict):
                pendencias.append({"idx": idx, **pend})

pendencias_df = pd.DataFrame(pendencias)

if not pendencias_df.empty:
    pendencias_agg = (
        pendencias_df
        .groupby("idx", as_index=False)
        .agg(
            qtde_pefin=("Valor", "count"),
            valor_pefin_total=("Valor", lambda s: pd.to_numeric(s, errors="coerce").sum()),
            modalidades_pefin=("Modalidade", lambda s: ",".join(sorted(set(s.dropna().astype(str))))),
        )
    )
else:
    pendencias_agg = pd.DataFrame(columns=["idx", "qtde_pefin", "valor_pefin_total", "modalidades_pefin"])

## Quebrar JSON - Request

In [11]:
request_parsed = credpago_df["request"].apply(
    lambda x: json.loads(x) if pd.notna(x) and x else None
)

request_valid = request_parsed.dropna()
request_df = pd.json_normalize(request_valid.tolist(), sep="_")
request_df.index = request_valid.index
request_df = request_df.add_prefix("request_")

# Unify old (snake_case) and new (camelCase) request schemas
REQUEST_FIELD_ALIASES = {
    "request_valorAluguel": ["request_valor_aluguel"],
    "request_imobiliariaId": ["request_imobiliaria_id"],
    "request_idExterno": ["request_id_externo"],
    "request_imovelTipo": ["request_imovel_tipo"],
    "request_principalDocument": ["request_pessoa_principal_documento"],
}

for target, sources in REQUEST_FIELD_ALIASES.items():
    existing_sources = [c for c in sources if c in request_df.columns]
    if not existing_sources and target not in request_df.columns:
        continue
    if target not in request_df.columns:
        request_df[target] = pd.NA
    for source in existing_sources:
        if target == "request_valorAluguel":
            request_df[target] = request_df[target].combine_first(
                pd.to_numeric(request_df[source], errors="coerce")
            )
        else:
            request_df[target] = request_df[target].combine_first(request_df[source])
        request_df = request_df.drop(columns=[source])

## Join Json's

In [12]:
EXPANDED_PREFIXES = ("message_", "pessoa_", "request_")
expanded_cols = [c for c in credpago_df.columns if c.startswith(EXPANDED_PREFIXES)]

base_df = credpago_df.loc[valid].drop(columns=expanded_cols, errors="ignore")

credpago_expandido = (
    base_df
    .join(contrato_df, how="left")
    .join(pessoa_df, how="left")
    .join(request_df, how="left")
    .reset_index(names="idx")
    .merge(pendencias_agg, on="idx", how="left")
    .drop(columns="idx")
)

In [13]:
cols_drop = [
    # ingestão
    "_sdc_table_version", "_sdc_received_at", "_sdc_sequence", "_sdc_batched_at",

    # json bruto / containers
    "json_retornado",
    "request",
    "message_pessoas", "message_scores", "message_ratings",
    "pessoa_scores", "pessoa_ratings", "message_blend3Variables",
    "request_priorDecisions", "request_dadosAusentes", "request_errosTecnicos",
    "request_outras_pessoas", "request_blend3Variables", "request_scores",

    # bronze redundante
    "score_bvs",
    "renda_considerada",
    "decisao_bureau",
    "limite_mensal",

    # prováveis duplicatas
    "id_externo",
    "data",
    "request_month",

    # operacional / baixo valor (old format only — safe to keep)
    "success", "message_manual", "message_node",
    "message_reaproveitamentoConsultaMotor", "message_savingBureauPowerCurve",
    "message_logs", "message_partnerIds",
    "message_errosTecnicos", "message_dadosAusentes",
    "pessoa_errosTecnicos", "pessoa_dadosAusentes",
    "message_rentGuaranteeConstraints_rent_coverage_multiplier",
    "message_rentGuaranteeConstraints_exit_cost_multiplier",
    "message_rentGuaranteeConstraints_commission_percent",
    "message_rentGuaranteeConstraints_version",
]

credpago_clean = credpago_expandido.drop(columns=[c for c in cols_drop if c in credpago_expandido.columns])

In [14]:
credpago_clean[
    (pd.to_datetime(credpago_clean["requested_at"]).dt.normalize() == "2026-07-03")
    & (credpago_clean["message_decisao"] == "BLEND_4")
][["message_blend3Variables_realEstatePc4HistoryOver100Contracts", "message_blend3Variables_cityPc4HistoryOver100Contracts"]]

Empty DataFrame
Columns: [message_blend3Variables_realEstatePc4HistoryOver100Contracts, message_blend3Variables_cityPc4HistoryOver100Contracts]
Index: []

## Escoragem Blend4

In [15]:
credpago_clean_rep = credpago_clean.replace({
    "request_imovelTipo": {"RESIDENCIAL": 1, "COMERCIAL": 0}, 
    "message_blend3Variables_hasPreviousContracts": {True: 1, False: 0},
    "message_blend3Variables_hadOverdueInvoiceInPreviousContracts": {True: 1, False: 0}
}
)

In [16]:
rename_dict = {
    "message_scores_BVS_CUSTOM_V2": "score_proposto__bvs",#
    "message_scores_HFT1": "SERASA_CHSV5",
    "pessoa_idade": "age",
    "request_imovelTipo": "property_type",
    "message_qtdeRestricoesContrato": "qtde_restricoes__consulta_realizada",
    "request_valorAluguel": "rental_value",
    "message_rendaConsideradaContrato": "income",
    "message_blend3Variables_realEstatePc4HistoryOver100Contracts": "agency_pc4_mais_100_contratos__pc_categorias",
    "message_blend3Variables_cityPc4HistoryOver100Contracts": "city_pc4_mais_100_contratos__pc_categorias",
    "message_blend3Variables_hasPreviousContracts": "flag_tem__contratos_anteriores",
    "message_blend3Variables_hadOverdueInvoiceInPreviousContracts": "flag_teve_boleto_atrasado__contratos_anteriores",
}

In [17]:
vars_blend4 = ['score_proposto__bvs', 'SERASA_CHSV5', 'age', 'property_type', 'qtde_restricoes__consulta_realizada', 'rental_value', 'income', 'agency_pc4_mais_100_contratos__pc_categorias', 'city_pc4_mais_100_contratos__pc_categorias', 'flag_tem__contratos_anteriores', 'flag_teve_boleto_atrasado__contratos_anteriores']

id_vars = ['contract_id', 'requested_at', 'CPF_CNPJ', 'message_decisao', 'message_blendRegressaoPredict']

In [18]:
df_predict = (credpago_clean_rep.copy()).rename(columns=rename_dict)
df_predict["REGRA_BLEND_4"] = np.where(
    df_predict["score_proposto__bvs"] <= 334,
    "E_BVS",
    "BLEND4",
)

df_predict["SCORE_BVS"] = df_predict["score_proposto__bvs"]
df_predict["SCORE_SERASA"] = df_predict["SERASA_CHSV5"]
df_predict["RENDA"] = df_predict["income"]

df_predict.head()

,CPF_CNPJ,contract_id,requested_at,data_ultima_consulta,qtd_proponentes,codigo_cidade_ibge,score_imobiliaria,model,id_consulta,id_funcionalidade,...,property_type,request_pessoa_principal_nome,request_ratingPoliciesResult,qtde_pefin,valor_pefin_total,modalidades_pefin,REGRA_BLEND_4,SCORE_BVS,SCORE_SERASA,RENDA
0,56102410068,4636770,2026-09-11,2026-09-11,2,4304705,NI,HVA3,6420378,15,...,1,NaN,NaN,2.0,3076.0,"FINANCIAMENT,OUTRAS OPER",BLEND4,NaN,NaN,7192.5
1,5251461054,4636834,2026-09-11,2026-09-11,2,4316907,NI,HVA3,6420456,15,...,1,NaN,NaN,NaN,NaN,NaN,BLEND4,NaN,NaN,3425.0
2,64712583053,4715383,2026-09-26,2026-09-26,1,4314902,NI,BLEND_4,6518668,30,...,1,NaN,NaN,NaN,NaN,NaN,BLEND4,516.0,325.0,4384.0
3,57566372815,4715444,2026-09-26,2026-09-26,1,4303103,NI,BLEND_4,6518733,30,...,1,NaN,NaN,NaN,NaN,NaN,BLEND4,416.0,248.0,7261.0
4,4207461450,4434613,2026-07-29,2026-07-29,1,3127701,B,BLEND3_3,6172739,35,...,1,NaN,NaN,NaN,NaN,NaN,BLEND4,NaN,NaN,8014.5

In [19]:
df_predict.groupby("REGRA_BLEND_4", dropna=False).size()

REGRA_BLEND_4
BLEND4    360234
E_BVS      19495
dtype: int64

In [20]:
df_predict.to_csv(ANALYTICS_DIR/"df_predict_blend4_pre.csv", index=False)

## Criacão das Variáveis

In [21]:
df_predict_vars = prepare_blend4_variables(df_predict)
df_predict_escorada = predict_blend4_1(df_predict_vars)

## Criar Rating Blend4

In [22]:
score = pd.to_numeric(df_predict_escorada["pred_blend4_1_to_score"], errors="coerce")

conditions = [
    score.between(480, 1000),
    score.between(443, 479),
    score.between(408, 442),
    score.between(343, 407),
    score.between(0, 342),
]

choices = ["A", "B", "C", "D", "E"]

df_predict_escorada["rating_manual_blend4"] = np.select(conditions, choices, default=None)

In [23]:
score = pd.to_numeric(df_predict_escorada["message_blendRegressaoPredict"], errors="coerce")

conditions = [
    score.between(480, 1000),
    score.between(443, 479),
    score.between(408, 442),
    score.between(343, 407),
    score.between(0, 342),
]

choices = ["A", "B", "C", "D", "E"]

df_predict_escorada["rating_json_blend4"] = np.select(conditions, choices, default=None)

## Salvar Base como se fosse Blend4

In [24]:
# df_predict_blend4 = df_predict_escorada[df_predict_escorada["message_decisao"] == "BLEND3_3"].copy()
# df_predict_blend4["message_decisao"] = df_predict_blend4["message_decisao"].replace("BLEND3_3", "BLEND4")

# cp_final_df = pd.concat([df_predict_escorada, df_predict_blend4])
cp_final_df = df_predict_escorada.copy()
cp_final_df

,CPF_CNPJ,contract_id,requested_at,data_ultima_consulta,qtd_proponentes,codigo_cidade_ibge,score_imobiliaria,model,id_consulta,id_funcionalidade,...,SERASA_CHSV5__normalized4_1,age__normalized4_1,qtde_restricoes__consulta_realizada__normalized4_1,income_commitment__normalized4_1,agency_pc4_mais_100_contratos__pc_categorias__normalized4_1,city_pc4_mais_100_contratos__pc_categorias__normalized4_1,pred_blend4_1,pred_blend4_1_to_score,rating_manual_blend4,rating_json_blend4
0,56102410068,4636770,2026-09-11,2026-09-11,2,4304705,NI,HVA3,6420378,15,...,0.000000,1.25,6.0,-0.458326,0.000000,0.000000,0.523841,476.0,B,None
1,5251461054,4636834,2026-09-11,2026-09-11,2,4316907,NI,HVA3,6420456,15,...,0.000000,-0.55,0.0,-0.433757,0.000000,0.000000,0.481095,519.0,A,None
2,64712583053,4715383,2026-09-26,2026-09-26,1,4314902,NI,BLEND_4,6518668,30,...,-0.416910,2.40,1.0,0.309932,0.000000,-0.363323,0.561171,439.0,C,C
3,57566372815,4715444,2026-09-26,2026-09-26,1,4303103,NI,BLEND_4,6518733,30,...,-0.641399,2.00,5.0,-0.706622,0.000000,1.757891,0.731549,268.0,E,E
4,4207461450,4434613,2026-07-29,2026-07-29,1,3127701,B,BLEND3_3,6172739,35,...,0.000000,0.45,0.0,-0.205550,-0.000144,1.185381,0.588932,411.0,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379724,9619384474,4511804,2026-08-14,2026-08-14,1,2408102,NI,BLEND3_4,6268153,33,...,0.000000,0.00,0.0,0.000000,0.000000,-0.185189,0.529420,471.0,B,None
379725,14853192697,4512104,2026-08-14,2026-08-14,1,4208906,C,BLEND3_4,6268502,33,...,0.000000,-0.30,0.0,2.633837,0.000000,-0.545157,0.553325,447.0,B,E
379726,73446769072,4519626,2026-08-17,2026-08-17,1,<NA>,NI,BLEND_4,6277686,37,...,-0.489796,2.40,0.0,2.063344,0.000000,-0.526761,0.696437,304.0,E,E
379727,2036055605,4520552,2026-08-17,2026-08-18,1,3138203,D,BLEND3_4,6284010,33,...,0.000000,-0.45,0.0,0.703972,0.000000,0.070242,0.530272,470.0,B,D
379728,2992163066,4528940,2026-08-18,2026-08-18,1,4316907,NI,BLEND3_4,6289005,33,...,0.000000,0.00,0.0,0.000000,0.000000,0.373592,0.524183,476.0,B,None

In [25]:
cp_final_df.groupby("message_decisao", dropna=False).size()

message_decisao
                            24
BLEND3_3                 94001
BLEND3_4                 98552
BLEND_4                 169673
BLEND_REGRESSAO_2026        15
BVS_CUSTOM                 204
BVS_CUSTOM_V2             2322
HFT1                       796
HVA3                     12601
HVA4                      1541
dtype: int64

In [26]:
bvs = pd.to_numeric(cp_final_df["SCORE_BVS"], errors="coerce")
score = pd.to_numeric(cp_final_df["pred_blend4_1_to_score"], errors="coerce")

conditions = [
    bvs <= 334,                         # corte customizado BVS → E
    score.between(763, 1000),           # 763 – 1000
    score.between(704, 762),            # 704 – 762
    score.between(653, 703),            # 653 – 703
    score.between(607, 652),            # 607 – 652
    score.between(562, 606),            # 562 – 606
    score.between(520, 561),            # 520 – 561
    score.between(480, 519),            # 480 – 519
    score.between(443, 479),            # 443 – 479
    score.between(408, 442),            # 408 – 442
    score.between(375, 407),            # 375 – 407
    score.between(343, 374),            # 343 – 374
    score.between(307, 342),            # 307 – 342
    score.between(0, 306),              # 0 – 306
]

choices = [
    "E.E",      # override BVS ≤ 334
    "1.A+",
    "2.A",
    "3.A",
    "4.B+",
    "5.B+",
    "6.B",
    "7.B",
    "8.C",
    "9.D+",
    "10.D",
    "11.D",
    "E-1.E",
    "E-2.E",
]

cp_final_df["rating_cl_pol_blend4"] = np.select(conditions, choices, default=None)

## Salvar

In [27]:
cp_final_df.groupby("REGRA_BLEND_4", dropna=False).size()

REGRA_BLEND_4
BLEND4    360234
E_BVS      19495
dtype: int64

In [28]:
cp_final_df.groupby("message_decisao", dropna=False).size()

message_decisao
                            24
BLEND3_3                 94001
BLEND3_4                 98552
BLEND_4                 169673
BLEND_REGRESSAO_2026        15
BVS_CUSTOM                 204
BVS_CUSTOM_V2             2322
HFT1                       796
HVA3                     12601
HVA4                      1541
dtype: int64

In [29]:
cp_final_df.groupby("model", dropna=False).size()

model
                            24
BLEND3_3                 94001
BLEND3_4                 98552
BLEND_4                 169673
BLEND_REGRESSAO_2026        15
BVS_CUSTOM                 204
BVS_CUSTOM_V2             2322
HFT1                       796
HVA3                     12601
HVA4                      1541
dtype: int64

In [30]:
cp_final_df.groupby("REGRA_BLEND_4", dropna=False).size()

REGRA_BLEND_4
BLEND4    360234
E_BVS      19495
dtype: int64

In [31]:
cp_final_df.to_csv(ANALYTICS_DIR/"df_predict_blend4.csv", index=False)

## PC Cidades e PC Imobiliária

In [32]:
# project_id = 'loft-dl-datascience'

# query_city = '''
# select * from loft-dl-datascience.ds_risk_cp.blend3_2__variavel_cidade
# '''

# df_city = pd.read_gbq(query_city, project_id=project_id)
# df_city.to_parquet(ANALYTICS_DIR/"df_city.parquet")

In [33]:
# project_id = 'loft-dl-datascience'

# query_agency = '''
# select * from loft-dl-datascience.ds_risk_cp.blend3_2__variavel_imobiliaria
# '''

# df_agency = pd.read_gbq(query_agency, project_id=project_id)
# df_agency.to_parquet(ANALYTICS_DIR/"df_agency.parquet")